import { useEffect, useState } from 'react';
import { Image, Text } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { Button, Field, Header, Screen, StateView } from '@/components/ui';
import { profileService } from '@/services/profileService';
import { useAuth } from '@/hooks/useAuth';
import { colors } from '@/theme/tokens';
export default function EditProfile(){ const {user}=useAuth(); const [name,setName]=useState(''),[username,setUsername]=useState(''),[avatar,setAvatar]=useState(''),[cover,setCover]=useState(''),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false); useEffect(()=>{ if(user) profileService.get(user.id).then(({data})=>{setName((data as any)?.display_name??'');setUsername((data as any)?.username??'');setAvatar((data as any)?.avatar_url??'');setCover((data as any)?.cover_url??'');});},[user]); if(!user) return <Screen><StateView title="تحتاج إلى تسجيل الدخول" /></Screen>; const pick=async(kind:'avatar'|'cover')=>{const perm=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!perm.granted){setError('يرجى السماح بالوصول للصور');return;} const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.9}); if(result.canceled||!result.assets[0]?.uri)return; const {publicUrl,error}=await profileService.uploadImage(user.id,result.assets[0].uri,kind); if(error)setError(error.message); else if (kind==='avatar') setAvatar(publicUrl); else setCover(publicUrl);}; const save=async()=>{setSaving(true); const {error}=await profileService.update(user.id,{display_name:name,username,avatar_url:avatar,cover_url:cover}); setSaving(false); if(error) setError(error.message); else router.back();}; return <Screen scroll><Header title="تعديل الملف" />{cover?<Image source={{uri:cover}} style={{height:160,borderRadius:28}}/>:null}{avatar?<Image source={{uri:avatar}} style={{height:92,width:92,borderRadius:46,alignSelf:'flex-end'}}/>:null}<Button variant="glass" title="تعديل الغلاف" onPress={()=>pick('cover')}/><Button variant="glass" title="تعديل الصورة الشخصية" onPress={()=>pick('avatar')}/><Field value={name} onChangeText={setName} placeholder="الاسم"/><Field value={username} onChangeText={setUsername} placeholder="اسم المستخدم"/>{error?<Text style={{color:colors.danger,textAlign:'right'}}>{error}</Text>:null}<Button title={saving?'جار الحفظ...':'حفظ'} onPress={save}/></Screen> }
