import { useEffect, useState } from 'react';
import { FlatList, Image, RefreshControl, Text } from 'react-native';
import { router } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { Card, Header, Screen, SkeletonList, StateView } from '@/components/ui';
import { newsService } from '@/services/newsService';
import { colors, spacing } from '@/theme/tokens';
import type { NewsArticle } from '@/types/api';
export default function News(){ const {t}=useTranslation(); const [items,setItems]=useState<NewsArticle[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null); const load=async()=>{setError(null); const {data,error}=await newsService.latest(); if(error) setError(error.message); else setItems(((data as any)?.articles ?? data ?? []) as NewsArticle[]); setLoading(false); setRefreshing(false);}; useEffect(()=>{load();},[]); return <Screen><Header title={t('news')} subtitle={t('latestNews')} />{loading?<SkeletonList/>:error?<StateView title={t('configError')} message={error} actionLabel={t('retry')} onAction={load}/>:<FlatList data={items} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load();}}/>} contentContainerStyle={{gap:spacing.md}} keyExtractor={(i)=>i.id} ListEmptyComponent={<StateView title={t('empty')} />} renderItem={({item})=><Card onPress={()=>router.push({pathname:'/news/[id]',params:{id:item.id,title:item.title,url:item.url,description:item.description ?? '', imageUrl:item.imageUrl ?? '', publishedAt:item.publishedAt}})}>{item.imageUrl?<Image source={{uri:item.imageUrl}} style={{height:150,borderRadius:14}}/>:null}<Text style={{color:colors.text,fontWeight:'800',fontSize:17,textAlign:'right'}}>{item.title}</Text><Text style={{color:colors.muted,textAlign:'right'}}>{item.sourceName}</Text></Card>}/>}</Screen> }
