import { useEffect, useState } from 'react';
import { Image, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Button, StateView } from '@/components/ui';
import { useAuth } from '@/hooks/useAuth';
import { profileService } from '@/services/profileService';
import { colors, shadows } from '@/theme/tokens';
const tabs=['نظرة عامة','الوقت','الأنواع','المنصات','الأشخاص'];
const glassWeb = Platform.select({ web: { backdropFilter: 'blur(22px)' } as any, default: {} });
export default function Profile(){ const {user,signOut}=useAuth(); const insets=useSafeAreaInsets(); const [profile,setProfile]=useState<any>(null); const [counts,setCounts]=useState({followers:0,following:0}); const [tab,setTab]=useState(tabs[0]); useEffect(()=>{if(user){profileService.get(user.id).then(({data})=>setProfile(data)); profileService.counts(user.id).then(setCounts);}},[user]); if(!user) return <View style={styles.shell}><View style={styles.phone}><StateView title="سجل الدخول لإدارة ملفك وقوائمك" actionLabel="تسجيل الدخول" onAction={()=>router.push('/auth/onboarding')} /></View></View>; return <View style={styles.shell}><View style={styles.phone}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.content,{paddingTop:Math.max(insets.top,12),paddingBottom:Math.max(insets.bottom+116,132)}]}>
    <View style={styles.cover}>{profile?.cover_url?<Image source={{uri:profile.cover_url}} style={styles.fill}/>:<View style={[styles.fill,{backgroundColor:'#cfd7df'}]}/>}<Pressable onPress={()=>router.push('/profile/edit')} style={styles.coverButton}><Text style={styles.coverButtonText}>تعديل الغلاف 📷</Text></Pressable></View>
    <View style={styles.avatarWrap}><Image source={profile?.avatar_url?{uri:profile.avatar_url}:undefined as any} style={styles.avatar}/><Pressable onPress={()=>router.push('/profile/edit')} style={styles.editAvatar}><Text>✎</Text></Pressable></View>
    <View style={styles.identity}><View><Text style={styles.name}>{profile?.display_name ?? 'عزيز'}</Text><Text style={styles.handle}>@{profile?.username ?? user.email?.split('@')[0]}</Text><View style={styles.followRow}><Text style={styles.follow}><Text style={styles.purple}>{counts.followers}</Text> متابع</Text><Text style={styles.follow}><Text style={styles.purple}>{counts.following}</Text> متابعة</Text><Text style={styles.badge}>عضو</Text></View></View><View style={styles.actionRow}>{['✧','🏆','⚙'].map((x,i)=><Pressable key={x} onPress={()=>i===2?router.push('/settings'):router.push('/profile/edit')} style={styles.square}><Text style={styles.squareText}>{x}</Text></Pressable>)}</View></View>
    <View style={styles.tabs}>{tabs.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[styles.tab,tab===x&&styles.tabActive]}><Text style={[styles.tabText,tab===x&&styles.tabTextActive]}>{x}</Text></Pressable>)}</View>
    <View style={styles.statRow}>{[['0 د','وقت المشاهدة'],['—','متوسط التقييم'],['0','المتابعات']].map(([n,l])=><View key={l} style={styles.stat}><Text style={styles.statNum}>{n}</Text><Text style={styles.muted}>{l}</Text></View>)}</View>
    <View style={styles.mediaStats}>{[['🎞','0','أفلام'],['▭','0','مسلسلات'],['🎮','0','ألعاب']].map(([ic,n,l])=><View key={l} style={styles.mediaCell}><Text style={styles.squareText}>{ic}</Text><Text style={styles.statNumSmall}>{n}</Text><Text style={styles.muted}>{l}</Text></View>)}</View>
    <Text style={styles.section}>النشاط</Text><View style={styles.activity}>{['جاري المشاهدة','تم المشاهدة','محدد','المتابعة','مؤجل','متوقف','متخلف','مسقط'].map(x=><View key={x} style={styles.activityItem}><Text style={styles.muted}>0  {x}</Text></View>)}</View>
    <Button variant="glass" title="تسجيل الخروج" onPress={signOut}/>
  </ScrollView></View></View> }
const styles=StyleSheet.create({shell:{flex:1,alignItems:'center',backgroundColor:colors.background},phone:{flex:1,width:'100%',maxWidth:460,overflow:'hidden'},content:{paddingHorizontal:14,gap:16},cover:{height:255,borderRadius:32,overflow:'hidden',backgroundColor:'#d9dee8',alignItems:'center',justifyContent:'flex-start'},fill:{width:'100%',height:'100%'},coverButton:{position:'absolute',top:72,paddingHorizontal:20,paddingVertical:12,borderRadius:18,backgroundColor:'rgba(255,255,255,.86)',...glassWeb},coverButtonText:{fontSize:18,fontWeight:'800',color:colors.text},avatarWrap:{marginTop:-76,marginLeft:20,width:116,height:116},avatar:{width:116,height:116,borderRadius:58,backgroundColor:'#111',borderWidth:4,borderColor:'#fff',...shadows.card},editAvatar:{position:'absolute',right:0,bottom:8,width:38,height:38,borderRadius:19,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},identity:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},name:{fontSize:25,fontWeight:'900',color:colors.text,textAlign:'right'},handle:{fontSize:16,color:colors.muted,textAlign:'right'},followRow:{flexDirection:'row-reverse',alignItems:'center',gap:12,marginTop:8},follow:{color:colors.muted},purple:{color:colors.primary,fontWeight:'900'},badge:{color:colors.primary,backgroundColor:'rgba(121,98,232,.12)',paddingHorizontal:18,paddingVertical:6,borderRadius:18,overflow:'hidden',fontWeight:'800'},actionRow:{flexDirection:'row-reverse',gap:10},square:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.82)',...glassWeb},squareText:{fontSize:24,color:colors.text},tabs:{flexDirection:'row-reverse',backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.86)',borderRadius:20,padding:6},tab:{flex:1,paddingVertical:10,borderRadius:16,alignItems:'center'},tabActive:{backgroundColor:'rgba(121,98,232,.12)'},tabText:{fontSize:14,fontWeight:'800',color:colors.muted},tabTextActive:{color:colors.primary},statRow:{flexDirection:'row-reverse',gap:12},stat:{flex:1,minHeight:104,borderRadius:20,backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.86)',alignItems:'center',justifyContent:'center',...glassWeb},statNum:{fontSize:32,fontWeight:'900',color:colors.text},statNumSmall:{fontSize:18,fontWeight:'900',color:colors.text},muted:{color:colors.muted,textAlign:'center'},mediaStats:{flexDirection:'row-reverse',backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.86)',borderRadius:22,paddingVertical:18},mediaCell:{flex:1,alignItems:'center',gap:4,borderLeftWidth:1,borderLeftColor:colors.border},section:{fontSize:18,fontWeight:'900',textAlign:'right',color:colors.text},activity:{flexDirection:'row-reverse',flexWrap:'wrap',backgroundColor:colors.glass,borderRadius:20,borderWidth:1,borderColor:colors.border,padding:14},activityItem:{width:'50%',paddingVertical:3,alignItems:'center'}});
