import { ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, spacing } from '@/theme/tokens';

export function Screen({ children }: { children: ReactNode }) { return <View style={styles.screen}>{children}</View>; }
export function Header({ title, subtitle }: { title: string; subtitle?: string }) { return <View style={styles.header}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.muted}>{subtitle}</Text> : null}</View>; }
export function StateView({ title, message, actionLabel, onAction, loading }: { title: string; message?: string; actionLabel?: string; onAction?: () => void; loading?: boolean }) { return <View style={styles.state}>{loading ? <ActivityIndicator color={colors.primary} /> : null}<Text style={styles.stateTitle}>{title}</Text>{message ? <Text style={styles.muted}>{message}</Text> : null}{actionLabel && onAction ? <Button title={actionLabel} onPress={onAction} /> : null}</View>; }
export function Button({ title, onPress, disabled }: { title: string; onPress?: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, disabled && styles.disabled]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
export function Card({ children, onPress, onLongPress }: { children: ReactNode; onPress?: () => void; onLongPress?: () => void }) { return <Pressable onPress={onPress} onLongPress={onLongPress} style={styles.card}>{children}</Pressable>; }
export function Field(props: { value: string; onChangeText: (v: string) => void; placeholder: string; multiline?: boolean }) { return <TextInput {...props} placeholderTextColor={colors.muted} style={[styles.input, props.multiline && styles.multiline]} textAlign="right" />; }
export function SkeletonList() { return <View style={{ gap: spacing.md }}>{[0,1,2].map((i) => <View key={i} style={styles.skeleton} />)}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background, padding: spacing.lg, gap: spacing.md }, header: { gap: spacing.xs, alignItems: 'flex-end' }, title: { color: colors.text, fontSize: 30, fontWeight: '800', textAlign: 'right' }, muted: { color: colors.muted, fontSize: 14, textAlign: 'right' }, state: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: spacing.md, padding: spacing.lg }, stateTitle: { color: colors.text, fontSize: 20, fontWeight: '700', textAlign: 'center' }, button: { backgroundColor: colors.primary, borderRadius: 14, paddingVertical: spacing.sm, paddingHorizontal: spacing.lg, alignItems: 'center' }, disabled: { opacity: 0.5 }, buttonText: { color: colors.background, fontWeight: '800' }, card: { backgroundColor: colors.surface, borderRadius: 18, padding: spacing.md, gap: spacing.sm }, input: { minHeight: 48, borderRadius: 14, backgroundColor: colors.surface, color: colors.text, padding: spacing.md }, multiline: { minHeight: 140, textAlignVertical: 'top' }, skeleton: { height: 96, borderRadius: 18, backgroundColor: colors.surface } });
