/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react';
import { Image, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AddToListBottomSheet } from '@/components/AddToListBottomSheet';
import { StateView } from '@/components/ui';
import { showAuthRequiredDialog } from '@/components/AuthRequiredDialog';
import { mediaService } from '@/services/mediaService';
import { useAuth } from '@/hooks/useAuth';
import { colors, shadows } from '@/theme/tokens';
import type { MediaType } from '@/types/database';
const glassWeb = Platform.select({ web: { backdropFilter: 'blur(22px)' } as any, default: {} });
const typeLabel = (t?: string) => t === 'tv' ? 'مسلسل' : t === 'game' ? 'لعبة' : 'فيلم';
export default function MediaDetails(){ const {t}=useTranslation(); const {user}=useAuth(); const insets=useSafeAreaInsets(); const p=useLocalSearchParams<{id:string;source:string;mediaType:MediaType}>(); const [item,setItem]=useState<any>(),[error,setError]=useState<string|null>(null),[sheet,setSheet]=useState(false); const load=async()=>{const {data,error}=await mediaService.details({source:p.source ?? 'tmdb',sourceId:p.id,mediaType:p.mediaType ?? 'movie'}); if(error) setError(error.message); else setItem((data as any)?.item ?? data);}; useEffect(()=>{load();},[p.id, p.source, p.mediaType]); if(error) return <View style={styles.shell}><StateView title={t('configError')} message={error} actionLabel={t('retry')} onAction={load}/></View>; if(!item) return <View style={styles.shell}><StateView loading title={t('loading')} /></View>; const listItem={id:item.id ?? p.id,source:item.source ?? p.source,sourceId:item.sourceId ?? p.id,mediaType:item.mediaType ?? p.mediaType,title:item.title,posterUrl:item.posterUrl,overview:item.overview,releaseDate:item.releaseDate}; const year=item.releaseDate?String(item.releaseDate).slice(0,4):undefined; const genres=(item.genres ?? item.genreNames ?? []).filter(Boolean); const cast=(item.cast ?? item.credits?.cast ?? []).slice(0,8); const director=(item.director ?? item.credits?.crew?.find?.((x:any)=>x.job==='Director')?.name); return <View style={styles.shell}><View style={styles.phone}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.content,{paddingTop:Math.max(insets.top+18,28),paddingBottom:Math.max(insets.bottom+116,132)}]}>
  <View style={styles.top}><Pressable onPress={()=>router.back()} style={styles.round}><Text style={styles.icon}>‹</Text></Pressable><Pressable style={styles.round}><Text style={styles.icon}>•••</Text></Pressable></View>
  {item.posterUrl?<><Image source={{uri:item.posterUrl}} style={styles.backdrop}/><Image source={{uri:item.posterUrl}} style={styles.poster}/></>:<View style={[styles.poster,styles.fallback]}/>}<Text style={styles.title}>{item.title}</Text>
  <Text style={styles.meta}>{[year, item.runtime ? `${item.runtime} د` : undefined, typeLabel(item.mediaType ?? p.mediaType), item.rating ? `⭐ ${Number(item.rating).toFixed(1)}` : undefined].filter(Boolean).join(' · ')}</Text>
  {director?<View style={styles.director}><View style={styles.avatar}/><View><Text style={styles.directorName}>{director}</Text><Text style={styles.muted}>المخرج</Text></View></View>:null}
  {cast.length?<><Text style={styles.linkTitle}>طاقم العمل</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.castRail}>{cast.map((c:any,i:number)=><View key={c.id??c.name??i} style={styles.cast}><View style={styles.castPhoto}>{c.profileUrl||c.profile_path?<Image source={{uri:c.profileUrl??`https://image.tmdb.org/t/p/w185${c.profile_path}`}} style={styles.castPhoto}/>:null}</View><Text numberOfLines={1} style={styles.castName}>{c.name}</Text></View>)}</ScrollView></>:null}
  {genres.length?<View style={styles.chips}>{genres.map((g:any)=><Text key={String(g.id??g.name??g)} style={styles.chip}>{g.name??g}</Text>)}</View>:null}
  <View style={styles.ratingRow}>{item.rating?<View style={styles.ratingCard}><Text style={styles.ratingValue}>{Number(item.rating).toFixed(1)}</Text><Text style={styles.muted}>التقييم</Text></View>:null}<View style={styles.ratingCard}><Text style={styles.ratingValue}>Refract</Text><Text style={styles.muted}>بطاقة تقييم</Text></View></View>
  {item.trailerUrl?<Pressable style={styles.trailer}><Text style={styles.buttonText}>شاهد الإعلان ▶</Text></Pressable>:null}<Pressable style={styles.primary} onPress={()=>user?setSheet(true):showAuthRequiredDialog()}><Text style={styles.primaryText}>أضف إلى قائمة المشاهدة</Text></Pressable>
  <View style={styles.actions}>{['قائمتي','قائمة','مشاركة','المزيد'].map(x=><View key={x} style={styles.action}><Text style={styles.icon}>☷</Text><Text style={styles.muted}>{x}</Text></View>)}</View>
  {item.overview?<View><Text style={styles.section}>نبذة عن {typeLabel(item.mediaType)}</Text><Text style={styles.overview}>{item.overview}</Text></View>:null}
  <AddToListBottomSheet visible={sheet} item={listItem} onClose={()=>setSheet(false)} />
</ScrollView></View></View> }
const styles=StyleSheet.create({shell:{flex:1,alignItems:'center',backgroundColor:colors.background},phone:{flex:1,width:'100%',maxWidth:460,overflow:'hidden'},content:{paddingHorizontal:22,gap:14,alignItems:'center'},top:{width:'100%',flexDirection:'row',justifyContent:'space-between'},round:{width:42,height:42,borderRadius:21,backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.82)',alignItems:'center',justifyContent:'center',...glassWeb},icon:{fontSize:22,color:colors.text},backdrop:{position:'absolute',top:0,width:'120%',height:310,opacity:.16},poster:{width:240,height:360,borderRadius:24,backgroundColor:'#d7dbe3',...shadows.card},fallback:{backgroundColor:'#d7dbe3'},title:{fontSize:31,fontWeight:'900',color:colors.text,textAlign:'center'},meta:{fontSize:14,color:colors.muted,textAlign:'center'},director:{width:'100%',flexDirection:'row-reverse',alignItems:'center',gap:12},avatar:{width:54,height:54,borderRadius:27,backgroundColor:'#d9dee8'},directorName:{fontSize:18,fontWeight:'800',color:colors.text,textAlign:'right'},muted:{color:colors.muted,textAlign:'center'},linkTitle:{alignSelf:'flex-end',color:colors.primary,fontWeight:'800',fontSize:15},castRail:{gap:14,paddingVertical:4},cast:{width:72,alignItems:'center',gap:6},castPhoto:{width:62,height:62,borderRadius:14,backgroundColor:'#d9dee8',overflow:'hidden'},castName:{fontSize:12,fontWeight:'700',color:colors.text,textAlign:'center'},chips:{width:'100%',flexDirection:'row-reverse',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:14,paddingVertical:8,borderRadius:18,backgroundColor:colors.glass,color:colors.text,overflow:'hidden'},ratingRow:{width:'100%',flexDirection:'row-reverse',gap:12},ratingCard:{flex:1,minHeight:58,borderRadius:16,backgroundColor:colors.glass,borderWidth:1,borderColor:'rgba(255,255,255,.82)',alignItems:'center',justifyContent:'center',...glassWeb},ratingValue:{fontSize:18,fontWeight:'900',color:colors.text},trailer:{width:'100%',height:54,borderRadius:16,backgroundColor:colors.glass,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border},buttonText:{fontSize:17,fontWeight:'800',color:colors.text},primary:{width:'100%',height:56,borderRadius:16,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:17,fontWeight:'900',color:'#fff'},actions:{width:'100%',flexDirection:'row-reverse',backgroundColor:colors.glass,borderRadius:18,borderWidth:1,borderColor:colors.border,overflow:'hidden'},action:{flex:1,alignItems:'center',paddingVertical:12,borderLeftWidth:1,borderLeftColor:colors.border},section:{fontSize:18,fontWeight:'900',color:colors.text,textAlign:'right'},overview:{fontSize:15,lineHeight:25,color:colors.muted,textAlign:'right'}});
